# Generated by Django 2.2.6 on 2020-10-14 13:47

import django.core.validators
from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', validators=[django.core.validators.validate_image_file_extension, posts.validators.validate_file_size]),
        ),
    ]
