# Generated by Django 2.2.6 on 2020-10-15 16:26

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201014_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', validators=[posts.validators.validate_file_size]),
        ),
    ]
